"""Parse an openCONFIGURATOR ``xap.xml`` into a process-image description.

``xap.xml`` (generated by openCONFIGURATOR / openCONFIGURATOR-Studio) describes
the managing node's process image: two ``<ProcessImage>`` blocks with a byte
``size`` and a list of ``<Channel>`` elements (name, datatype, bit size, byte
offset). This module turns that into typed channel lists plus the two image
sizes, which :mod:`openpowerlink.stack` uses to allocate the image and to know
where each digital/analog channel lives.

openPOWERLINK direction convention (mirrored here):
  * ``type="output"`` = data the MN reads FROM the CN = **inputs** (DI/AI)
  * ``type="input"``  = data the MN writes TO   the CN = **outputs** (DO/AO)
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path


class ChannelKind(Enum):
    DIGITAL = "digital"
    ANALOG = "analog"


@dataclass(frozen=True)
class Channel:
    """One process-image channel."""

    name: str
    kind: ChannelKind
    byte_offset: int          # offset within the image (bytes)
    bit_size: int             # 8 for a digital byte, 16/32 for analog
    signed: bool

    @property
    def byte_size(self) -> int:
        return (self.bit_size + 7) // 8


@dataclass
class ProcessImage:
    """The parsed process image: inputs (CN->MN) and outputs (MN->CN)."""

    input_size: int = 0                       # PI_OUT size (bytes): CN -> MN
    output_size: int = 0                      # PI_IN size (bytes):  MN -> CN
    inputs: list[Channel] = field(default_factory=list)
    outputs: list[Channel] = field(default_factory=list)

    @property
    def digital_inputs(self) -> list[Channel]:
        return [c for c in self.inputs if c.kind is ChannelKind.DIGITAL]

    @property
    def analog_inputs(self) -> list[Channel]:
        return [c for c in self.inputs if c.kind is ChannelKind.ANALOG]

    @property
    def digital_outputs(self) -> list[Channel]:
        return [c for c in self.outputs if c.kind is ChannelKind.DIGITAL]

    @property
    def analog_outputs(self) -> list[Channel]:
        return [c for c in self.outputs if c.kind is ChannelKind.ANALOG]


class XapError(Exception):
    """Raised when an xap.xml cannot be parsed."""


def _ln(el: ET.Element) -> str:
    tag = el.tag
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def _classify(name: str, data_type: str) -> ChannelKind:
    """A channel is digital when its name mentions Digital, else analog."""
    lname = name.lower()
    if "digital" in lname:
        return ChannelKind.DIGITAL
    if "analog" in lname or "analogue" in lname:
        return ChannelKind.ANALOG
    # Fall back on the datatype width: 8-bit unsigned => treat as digital byte.
    return ChannelKind.DIGITAL if data_type.lower().startswith("unsigned8") \
        else ChannelKind.ANALOG


def _channel(el: ET.Element) -> Channel:
    name = el.attrib.get("Name", "")
    data_type = el.attrib.get("dataType", "")
    bit_size = int(el.attrib.get("dataSize", "8"))
    offset_raw = el.attrib.get("PIOffset", "0x0000")
    byte_offset = int(offset_raw, 0)      # honours the 0x prefix
    signed = data_type.lower().startswith("integer")
    return Channel(name=name, kind=_classify(name, data_type),
                   byte_offset=byte_offset, bit_size=bit_size, signed=signed)


def parse_xap(source: str | Path) -> ProcessImage:
    """Parse an ``xap.xml`` file path or XML string into a :class:`ProcessImage`."""
    try:
        if isinstance(source, (str, Path)) and Path(str(source)).is_file():
            root = ET.parse(str(source)).getroot()
        else:
            root = ET.fromstring(str(source))
    except (ET.ParseError, OSError) as exc:
        raise XapError(f"cannot parse xap.xml: {exc}") from exc

    image = ProcessImage()
    for pi in root:
        if _ln(pi) != "ProcessImage":
            continue
        pi_type = pi.attrib.get("type", "")
        size = int(pi.attrib.get("size", "0"))
        channels = [_channel(ch) for ch in pi if _ln(ch) == "Channel"]
        if pi_type == "output":          # MN reads FROM CN => inputs
            image.input_size = size
            image.inputs = channels
        elif pi_type == "input":         # MN writes TO CN => outputs
            image.output_size = size
            image.outputs = channels
    if not image.inputs and not image.outputs:
        raise XapError("xap.xml contained no ProcessImage channels")
    return image
